version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - API_KEY=mysecretkey

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
